### 线性回归 Linear Regression

#### 应用场景
- 房价预测
- 销售额度预测
- 贷款额度预测
#### 原理
线性回归（Linear Regression）是利用回归方程（函数）对一个或多个自变量（特征值）和因变量（目标值）之间关系进行建模的一种分析方程。

- 单变量回归：只有一个自变量
- 多元回归：多个自变量
通用公式  
$$h(w)=w_1x_1+w_2x_2+w_3x_3\dots+b=w^Tx+b$$
其中$w,x$可以理解为矩阵：$w=\begin{pmatrix}b\\w_1\\w_2\end{pmatrix},x=\begin{pmatrix}1\\x_1\\x_2\end{pmatrix}$,$b$为偏置  
其实就是$y=kx+b$

- 找到特征值与目标值间函数关系，这个关系可以理解为线性模型
广义的线性模型：
- 线性关系：单特征与目标值的关系呈直线关系，两个特征与目标值呈现平面关系
- 非线性关系：不能用一个直线或平面来拟合
- ***线性关系一定是线性模型***
- ***线性模型不一定是线性关系***

我们应该怎样从一大堆数据里求出回归方程呢？ 假定输入数据存放在矩阵 $x$ 中，而回归系数存放在向量 $w$ 中。那么对于给定的数据 $X1$，预测结果将会通过 $Y = X1^T w$给出。现在的问题是，手里有一些 $X$ 和对应的 $y$，怎样才能找到 $w$ 呢？一个常用的方法就是找出使误差最小的 $w$ 。这里的误差是指预测 $y$ 值和真实 $y$ 值之间的差值，使用该误差的简单累加将使得正差值和负差值相互抵消，所以我们采用平方误差（实际上就是我们通常所说的最小二乘法）。

### 损失和优化
目标:求模型参数  
模型参数能够使得预测准确  

例如，假设某房屋价格与环境参数存在如下关系：
- $真实房价=0.02*中心区域距离+0.04*城市一氧化氮浓度\dots$  

那么现在我们随意指定（猜测）一个关系

- $预测房价=0.25*中心区域距离+0.14*城市一氧化氮浓度\dots$

真实值和预测结果是存在一定误差的，衡量误差的函数便是：损失函数

损失函数:
一般是最小二乘法（又称最小平方法）一种数学优化技术。它通过最小化误差的平方和寻找数据的最佳函数匹配。

如何去求模型的 $w$ ,使得损失最小？  
线性回归常用优化算法：
- 正规方程 Normal Equation （较少使用）
  - 可以比喻成一个天才
  - 当特征过多过复杂时，求解速度太慢并且得不到结果
  - 小数据场景有优势
  - 直接求解$w$，$X$为特征值矩阵，$y$为目标值矩阵，直接求的最好结果
$$w = (X^TX)^{-1}X^Ty$$



- 梯度下降 Gradient Descent（较多使用）
  - 可以比喻成是勤奋努力的普通人
  - 不断地改进、试错直到成功
  - $\alpha$ 为学习速率，需要手动指定，$\alpha$右边整体表示函数下降的方向
  - 面对规模十分庞大的数据集，能找到较好的结果
$$
w1 := w1 - \alpha\frac{{\partial}cost(w0+w1x1)}{{\partial}w1}
$$
$$
w0 := w0 - \alpha\frac{{\partial}cost(w0+w1x1)}{{\partial}w1}
$$

### API
~~~python
sklearn.linear_model.LinearRegression
~~~
- 通过正规方程优化
- fit_intercept: 是否计算偏置
- LinearRegression.coef_: 回归系数
- LinearRegression.intercept_: 偏置

~~~python
sklearn.linear_model.SGDRegressor
~~~
- SGDRegressor 类实现了随机梯度下降学习，支持不同的loss函数和正则化惩罚项来拟合线性回归模型
- loss:损失类型
  - squared_error：普通最小二乘法
  - huber
  - epsilon_insensitive
  - squared_epsilon_insensitive
- fit_intercept: 是否计算偏置
- learning_rate: 学习率的算法，eta是学习率
  - ‘constant’: eta = eta0
  - ‘optimal’: eta = 1.0 / (alpha * (t + t0))
  - ‘invscaling’: eta = eta0 / pow(t, power_t) 逐步减小学习率
    - power_t：默认是0.25
  - ‘adaptive’: eta = eta0
- SGDRegressor.coef_: 回归系数
- SGDRegressor.intercept_: 偏置

### 梯度下降方法
- 梯度下降（Gradient Descent）
  - 原始的梯度下降法需要计算所有样本的值才能够得出梯度，计算量大。
- 随机梯度下降（SGD，Stochastic gradient descent）
  - 每次迭代时只考虑一个训练样本
  - 优点是：高效，容易实现
  - 缺点是：需要设置许多超参数，如正则项参数，迭代数，SGD对特征标准化敏感
- 随机平均梯度法（SAG，Stochastic Average Gradient）
  - 岭回归、逻辑回归中有SAG优化

In [10]:
# Boston house price
# length: 506
# CRIM - 城镇人均犯罪率                                                              ------【城镇人均犯罪率】
# ZN - 占地面积超过25,000平方英尺的住宅用地比例。               ------【住宅用地所占比例】
# INDUS - 每个城镇非零售业务的比例。                                      ------【城镇中非商业用地占比例】
# CHAS - Charles River虚拟变量（如果是河道，则为1;否则为0  ------【查尔斯河虚拟变量，用于回归分析】
# NOX - 一氧化氮浓度（每千万份）                                             ------【环保指标】
# RM - 每间住宅的平均房间数                                                      ------【每栋住宅房间数】
# AGE - 1940年以前建造的自住单位比例                                     ------【1940年以前建造的自住单位比例 】
# DIS -波士顿的五个就业中心加权距离                                        ------【与波士顿的五个就业中心加权距离】
# RAD - 径向高速公路的可达性指数                                             ------【距离高速公路的便利指数】
# TAX - 每10,000美元的全额物业税率                                          ------【每一万美元的不动产税率】
# PTRATIO - 城镇的学生与教师比例                                             ------【城镇中教师学生比例】
# B - 1000（Bk - 0.63）^ 2其中Bk是城镇黑人的比例                   ------【城镇中黑人比例】
# LSTAT - 人口状况下降％                                                            ------【房东属于低等收入阶层比例】
# MEDV - 自有住房的中位数报价, 单位1000美元                         ------【自住房屋房价中位数】



In [11]:
# 获取数据集
import pandas as pd
import numpy as np
from sklearn.datasets import load_boston
boston = load_boston()
boston.data.shape


D:\source\tools\miniconda\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset 

(506, 13)

In [12]:
# 划分数据集
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(boston.data,boston.target,random_state=22)
x_train

array([[1.80028e+00, 0.00000e+00, 1.95800e+01, ..., 1.47000e+01,
        2.27610e+02, 1.21400e+01],
       [2.14090e-01, 2.20000e+01, 5.86000e+00, ..., 1.91000e+01,
        3.77070e+02, 3.59000e+00],
       [2.99160e-01, 2.00000e+01, 6.96000e+00, ..., 1.86000e+01,
        3.88650e+02, 1.30000e+01],
       ...,
       [4.41700e-02, 7.00000e+01, 2.24000e+00, ..., 1.48000e+01,
        3.90860e+02, 6.07000e+00],
       [5.90050e-01, 0.00000e+00, 2.18900e+01, ..., 2.12000e+01,
        3.85760e+02, 1.11200e+01],
       [1.11081e+01, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.96900e+02, 3.47700e+01]])

In [13]:
# 标准化
from sklearn.preprocessing import StandardScaler
std = StandardScaler()
x_train = std.fit_transform(x_train)
x_test = std.transform(x_test)
x_train

array([[-0.20918739, -0.52054534,  1.24477931, ..., -1.72807526,
        -1.35897227, -0.08447646],
       [-0.43088174,  0.3974553 , -0.7606374 , ...,  0.30003249,
         0.24261973, -1.25661718],
       [-0.41899191,  0.3140007 , -0.59985326, ...,  0.0695657 ,
         0.36670935,  0.03342307],
       ...,
       [-0.45463067,  2.4003658 , -1.28976339, ..., -1.6819819 ,
         0.3903914 , -0.91662782],
       [-0.37833557, -0.52054534,  1.582426  , ...,  1.26799301,
         0.33574053, -0.22431079],
       [ 1.09172307, -0.52054534,  1.02845156, ...,  0.80705943,
         0.45511517,  3.0179264 ]])

In [14]:
# 预估器

# 使用正规方程优化
from sklearn.linear_model import LinearRegression
line = LinearRegression()
line.fit(x_train, y_train)
print("line coef_:",line.coef_)
print("line intercept_:",line.intercept_)

line_pred = line.predict(x_test)
line_pred



line coef_: [-0.64817766  1.14673408 -0.05949444  0.74216553 -1.95515269  2.70902585
 -0.07737374 -3.29889391  2.50267196 -1.85679269 -1.75044624  0.87341624
 -3.91336869]
line intercept_: 22.62137203166228


array([28.22944896, 31.5122308 , 21.11612841, 32.6663189 , 20.0023467 ,
       19.07315705, 21.09772798, 19.61400153, 19.61907059, 32.87611987,
       20.97911561, 27.52898011, 15.54701758, 19.78630176, 36.88641203,
       18.81202132,  9.35912225, 18.49452615, 30.66499315, 24.30184448,
       19.08220837, 34.11391208, 29.81386585, 17.51775647, 34.91026707,
       26.54967053, 34.71035391, 27.4268996 , 19.09095832, 14.92742976,
       30.86877936, 15.88271775, 37.17548808,  7.72101675, 16.24074861,
       17.19211608,  7.42140081, 20.0098852 , 40.58481466, 28.93190595,
       25.25404307, 17.74970308, 38.76446932,  6.87996052, 21.80450956,
       25.29110265, 20.427491  , 20.4698034 , 17.25330064, 26.12442519,
        8.48268143, 27.50871869, 30.58284841, 16.56039764,  9.38919181,
       35.54434377, 32.29801978, 21.81298945, 17.60263689, 22.0804256 ,
       23.49262401, 24.10617033, 20.1346492 , 38.5268066 , 24.58319594,
       19.78072415, 13.93429891,  6.75507808, 42.03759064, 21.92

In [15]:
# 使用梯度下降优化
from sklearn.linear_model import SGDRegressor
sgd = SGDRegressor()
sgd.fit(x_train, y_train)
print("sgd coef_:",sgd.coef_)
print("sgd intercept_:",sgd.intercept_)

sgd_pred = sgd.predict(x_test)
sgd_pred

sgd coef_: [-0.47164946  0.84810581 -0.4221744   0.82214427 -1.56692709  2.87175833
 -0.14959994 -2.99664564  1.55990926 -0.83326476 -1.68637887  0.89296662
 -3.87746099]
sgd intercept_: [22.64276849]


array([28.35283663, 31.54637077, 21.47491967, 32.75646174, 20.3418425 ,
       19.29446058, 21.36624875, 19.47855402, 19.73561328, 32.82279733,
       21.3507788 , 27.36004763, 15.68800001, 20.09589517, 37.10427405,
       18.5428127 ,  9.87382737, 18.69597346, 30.81744182, 24.26600453,
       19.25396239, 34.03095316, 29.59424714, 17.55575506, 34.74764334,
       26.3510561 , 34.10873088, 27.3125338 , 19.33301543, 15.91182652,
       30.76065113, 14.40884207, 37.33781468,  9.2308758 , 16.48122096,
       16.88240854,  8.07755489, 19.91315668, 40.53363643, 29.24633927,
       25.27684054, 18.03776184, 39.72276732,  6.84276548, 21.63314443,
       24.94440225, 21.15763781, 20.80655367, 17.07290349, 26.57373272,
        9.85179393, 27.03746744, 30.735683  , 16.95776741,  9.74698534,
       35.3966156 , 31.21061938, 23.02185615, 17.62052505, 21.88401492,
       23.59321351, 23.85375653, 20.44220105, 38.06950276, 25.77576132,
       19.83708875, 14.35199226,  6.88975798, 42.71285914, 21.80

In [21]:
# 网格搜索对梯度下降调参
from sklearn.model_selection import GridSearchCV
estimator = SGDRegressor()
params = {
    "penalty":["l2","l1"],
    "learning_rate":["constant","optimal","invscaling","adaptive"],
    "eta0":[0.1,0.05,0.01,0.005,0.001],
    "max_iter":[500,800,1000,5000,10000,20000,50000]
}
grid = GridSearchCV(estimator,params,cv=3,n_jobs=-1)
grid.fit(x_train, y_train)
print("best_params_",grid.best_params_)
print("best_score_",grid.best_score_)


sgdGS = SGDRegressor(eta0=grid.best_params_["eta0"],learning_rate=grid.best_params_["learning_rate"],penalty=grid.best_params_["penalty"],max_iter=grid.best_params_["max_iter"])
sgdGS.fit(x_train, y_train)


print("sgdGS coef_:",sgdGS.coef_)
print("sgdGS intercept_:",sgdGS.intercept_)


sgdGS_pred = sgdGS.predict(x_test)
sgdGS_pred

best_params_ {'eta0': 0.01, 'learning_rate': 'constant', 'max_iter': 50000, 'penalty': 'l1'}
best_score_ 0.7004690762216201
sgdGS coef_: [-0.00602056  1.38560729 -0.03802939  1.54275532 -2.02685416  3.35396475
 -0.20073693 -3.25456587  2.7293583  -1.54110265 -1.86376158  0.57077494
 -4.31436139]
sgdGS intercept_: [22.83663945]


array([27.97880973, 31.58264544, 20.13298324, 36.12434121, 19.19334954,
       19.46754043, 19.94108356, 18.38035793, 18.68311012, 33.51539277,
       19.90465573, 28.99797756, 13.86494221, 18.93850598, 38.54000505,
       17.24303266,  7.04890975, 17.34242382, 31.07526375, 24.11196777,
       19.37889203, 34.5752468 , 32.57044789, 18.60302102, 35.41909387,
       25.56743415, 36.06208055, 27.98298053, 20.31165987, 14.06562168,
       30.91927924, 13.58415368, 39.44333995, 14.83309218, 14.79647148,
       17.18057434,  9.11638119, 20.44893909, 45.39067719, 29.24705634,
       24.87823977, 18.75606998, 45.40327997,  5.9671942 , 22.29149707,
       24.64158046, 22.23521007, 19.7341643 , 18.25633081, 28.80643758,
        6.91116548, 27.24494423, 33.85481775, 18.19380296, 11.11067092,
       36.07062765, 33.12803101, 21.66148332, 16.07814946, 21.98615985,
       23.03680447, 23.03639171, 19.17959546, 39.91764422, 24.73385947,
       20.07262826, 15.60981783,  6.58428582, 47.45149148, 21.29