In [3]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.7.0


In [4]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11501568/11490434 [==============================] - 2s 0us/step


In [5]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [7]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.6030581 , -0.7105401 ,  0.03247918,  0.17695332, -0.23444295,
         0.85401547,  0.35059536,  0.41662744, -0.19619048,  0.27486643]],
      dtype=float32)

In [9]:
tf.nn.softmax(predictions).numpy()

array([[0.04765936, 0.04280252, 0.0899826 , 0.10396876, 0.06890262,
        0.2046196 , 0.12368432, 0.13212714, 0.07158937, 0.11466371]],
      dtype=float32)

In [11]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [12]:
loss_fn(y_train[:1], predictions).numpy()

1.5866027

In [13]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [16]:
model.fit(x_train, y_train, epochs=15)

Epoch 1/15
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0303 - accuracy: 0.9895
Epoch 2/15
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0285 - accuracy: 0.9901
Epoch 3/15
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0270 - accuracy: 0.9906
Epoch 4/15
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0256 - accuracy: 0.9910
Epoch 5/15
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0260 - accuracy: 0.9913
Epoch 6/15
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0256 - accuracy: 0.9915
Epoch 7/15
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0241 - accuracy: 0.9916
Epoch 8/15
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0222 - accuracy: 0.9924
Epoch 9/15
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0237 - accuracy: 0.9915
Epoch 10/15
1875/1875 [==============================] - 2s 1ms/step - loss: 0.022

In [17]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0866 - accuracy: 0.9795 - 343ms/epoch - 1ms/step


[0.08656476438045502, 0.9794999957084656]

In [18]:
model.predict(x_test)

array([[-21.874552  , -20.100832  , -15.338499  , ...,  14.344086  ,
        -14.98997   ,  -1.1310833 ],
       [ -9.437664  ,  -7.704792  ,  19.73179   , ..., -46.52011   ,
        -10.21374   , -57.838406  ],
       [-22.95237   ,  10.6097975 ,  -2.4324167 , ...,  -4.7540193 ,
         -3.5899105 , -20.335548  ],
       ...,
       [-38.223663  , -30.249802  , -31.184275  , ...,  -0.39932847,
         -5.6503143 ,   2.6615844 ],
       [-27.609118  , -33.723293  , -36.89914   , ..., -12.932465  ,
         -3.132928  , -20.053223  ],
       [-15.663222  , -36.65502   , -14.097044  , ..., -26.284243  ,
        -13.795318  , -18.947517  ]], dtype=float32)

In [24]:
model(x_test)

<tf.Tensor: shape=(10000, 10), dtype=float32, numpy=
array([[-21.874554 , -20.100832 , -15.338503 , ...,  14.344085 ,
        -14.989968 ,  -1.1310824],
       [ -9.437666 ,  -7.704795 ,  19.731789 , ..., -46.520103 ,
        -10.213738 , -57.8384   ],
       [-22.952368 ,  10.6097975,  -2.4324164, ...,  -4.754019 ,
         -3.58991  , -20.33555  ],
       ...,
       [-38.223663 , -30.249804 , -31.184278 , ...,  -0.3993284,
         -5.6503158,   2.6615837],
       [-27.609121 , -33.723293 , -36.89914  , ..., -12.932463 ,
         -3.1329288, -20.053225 ],
       [-15.66322  , -36.655018 , -14.097047 , ..., -26.284243 ,
        -13.795316 , -18.94752  ]], dtype=float32)>

In [20]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [21]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.86399420e-16, 1.09841030e-15, 1.28533198e-13, 2.39918137e-07,
        5.07573616e-18, 8.12440566e-12, 3.45258177e-18, 9.99999523e-01,
        1.82130745e-13, 1.90203991e-07],
       [2.14717621e-13, 1.21462183e-12, 1.00000000e+00, 4.04313139e-13,
        3.81846040e-38, 6.73486197e-11, 1.82519364e-12, 1.68719588e-29,
        9.88145180e-14, 2.04970330e-34],
       [2.65543601e-15, 9.99996781e-01, 2.16689205e-06, 8.74411932e-11,
        4.10960403e-08, 3.78409221e-10, 2.66033107e-09, 2.12607404e-07,
        6.80995413e-07, 3.63585064e-14],
       [9.99999404e-01, 4.37350521e-14, 7.46889555e-08, 4.09163502e-11,
        5.61363109e-12, 3.93886346e-09, 3.53740063e-07, 1.13734870e-07,
        1.44044707e-11, 2.59497690e-09],
       [1.12236815e-12, 9.57624877e-26, 6.54881661e-12, 1.09618226e-16,
        9.98687565e-01, 5.26498841e-14, 3.60678043e-10, 2.35665034e-08,
        4.56367366e-12, 1.31242140e-03]], dtype=float32)>