In [1]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier

In [2]:
X, y = load_iris(return_X_y=True)
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [3]:
len(set(y))

3

In [4]:
# Add noisy features
random_state = np.random.RandomState(0)
n_samples, n_features = X.shape

noise=random_state.randn(n_samples, 20 * n_features)
#noise=random_state.randn(2, 3 * 3)
#print(noise)



In [5]:

X = np.concatenate([X, noise], axis=1)


# Limit to the two first classes, and split into training and test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.5, random_state=random_state
)


In [6]:
classifier = RandomForestClassifier(max_depth=2, random_state=0,n_estimators=500,max_features=3)

# classifier = make_pipeline(StandardScaler(), LinearSVC(random_state=random_state))
classifier.fit(X_train, y_train)

RandomForestClassifier(max_depth=2, max_features=3, n_estimators=500,
                       random_state=0)

In [7]:
y_score = classifier.predict(X_test)

In [8]:
y_score

array([1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 2, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 2, 1, 1, 2, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1])

In [9]:
y_test

array([2, 0, 1, 1, 0, 0, 2, 1, 2, 2, 0, 0, 2, 0, 2, 1, 0, 0, 2, 1, 2, 0,
       2, 2, 2, 2, 0, 1, 0, 2, 2, 2, 1, 1, 0, 0, 1, 1, 2, 1, 2, 1, 2, 0,
       0, 0, 1, 0, 2, 1, 0, 2, 1, 0, 2, 2, 1, 0, 0, 1, 2, 1, 2, 2, 2, 0,
       0, 1, 2, 1, 0, 2, 1, 1, 1])

In [10]:
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
n_classes = len(set(y))


In [11]:
recall = recall_score(y_test, y_score, average=None)
recall

array([1.        , 1.        , 0.10714286])

In [12]:
precision = precision_score(y_test, y_score, average=None)
precision

array([0.92307692, 0.5       , 1.        ])

In [13]:
recall_micro = recall_score(y_test, y_score, average="micro")
recall_micro

0.6666666666666666

In [14]:
precision_micro = precision_score(y_test, y_score, average="micro")
precision_micro

0.6666666666666666

In [15]:
recall_macro = recall_score(y_test, y_score, average="macro")
recall_macro

0.7023809523809524

In [16]:
precision_macro = precision_score(y_test, y_score, average="macro")
precision_macro

0.8076923076923078